apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nexus-https-gitops
  description: This is GitOps manifest for nexus-https   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nexus-https
    janus-idp.io/tekton: nexus-https 
    backstage.io/kubernetes-id: nexus-https 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nexus-https
