apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nexus-https
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nexus-https 
  name: nexus-https
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nexus-https
    weight: 100 
