apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nexus-https
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nexus-https 
  name: nexus-https
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nexus-https 
